// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTBSKGa5dLbmws5CWJkZeNslms2Or1D_0',
    appId: '1:122310440737:web:7360d464208a683ac2b060',
    messagingSenderId: '122310440737',
    projectId: 'mykanjee-55ea0',
    authDomain: 'mykanjee-55ea0.firebaseapp.com',
    storageBucket: 'mykanjee-55ea0.appspot.com',
    measurementId: 'G-08XNERCTJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCurx2pf3NXFbCIOj6ze6hZ-BmtfPaQc_c',
    appId: '1:122310440737:android:7d82a36ebe865f9dc2b060',
    messagingSenderId: '122310440737',
    projectId: 'mykanjee-55ea0',
    storageBucket: 'mykanjee-55ea0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD6ick7pAsXDXTxUbrHUfI2G4J97y10_w',
    appId: '1:122310440737:ios:20c382155c457e98c2b060',
    messagingSenderId: '122310440737',
    projectId: 'mykanjee-55ea0',
    storageBucket: 'mykanjee-55ea0.appspot.com',
    iosClientId: '122310440737-38nnsf5q9dl4qod2fkpjtfc0hbo2h8mg.apps.googleusercontent.com',
    iosBundleId: 'com.example.vendor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD6ick7pAsXDXTxUbrHUfI2G4J97y10_w',
    appId: '1:122310440737:ios:2338356bdb588b61c2b060',
    messagingSenderId: '122310440737',
    projectId: 'mykanjee-55ea0',
    storageBucket: 'mykanjee-55ea0.appspot.com',
    iosClientId: '122310440737-00m1fc7broc6ktu5lv3pj2oubv5viq8e.apps.googleusercontent.com',
    iosBundleId: 'com.example.vendor.RunnerTests',
  );
}
